# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '012-NotificationTimer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 012-NotificationTimer
  pod 'RealmSwift', '~> 3.18.0'


end
